# Generated by Django 2.1 on 2018-08-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0087_auto_20180824_1603'),
        ('mainapp', '0086_merge_20180824_1601'),
    ]

    operations = [
    ]
