# Generated by Django 2.1 on 2018-08-25 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0089_ngo_website_url'),
        ('mainapp', '0089_person_is_dup'),
    ]

    operations = [
    ]
