# Generated by Django 2.1 on 2018-08-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0090_merge_20180825_1210'),
        ('mainapp', '0090_auto_20180825_1221'),
    ]

    operations = [
    ]
